<?php

// This code is generated by OWMigration

class OWMigration_v002 {
	public function up( ) {
        $migration = new OWMigrationRole( );
        $migration->startMigrationOn( 'Editor Exemple' );
        $migration->createIfNotExists( );
 
        $migration->addPolicy( 'content', '*' );
        $migration->addPolicy( 'user', 'login' );
        $migration->addPolicy( 'ezdhtml', '*' );
        $migration->assignToUserGroup( 'Editors', 'Subtree', '/1/2/' );
        $migration->assignToUserGroup( 'Editors', 'Subtree', '/1/43/' );
        $migration->end( );
    }
 
    public function down( ) {
        $migration = new OWMigrationRole( );
        $migration->startMigrationOn( 'Editor Exemple' );
        $migration->removeRole( );
    }
}

?>